version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: simpliLatamChallenge
    ports:
      - "5435:5432"
    networks:
      - backend-network

  backend:
    image: back-sl-challenge
    restart: always
    ports:
      - "8087:8087"
    environment:
      - DATABASE_URL=postgres://root:root@db:5432/simpliLatamChallenge
    depends_on:
      - db
    networks:
      - backend-network
  frontend:
    image: front-sl-challenge
    restart: always
    ports:
      - "8090:8080"
    depends_on:
      - backend
    networks:
      - backend-network
  # postman:
  #   image: postman/newman:alpine
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - backend-network

networks:
  backend-network:
