version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: simpliLatamChallenge
    ports:
      - "5435:5432"
    networks:
      - backend-network

  backend:
    image: back-sl-challenge
    restart: always
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgres://root:root@db:5432/simpliLatamChallenge
    depends_on:
      - db
    networks:
      - backend-network

networks:
  backend-network:
